nixpacks.providers = ["python"]

[start]
cmd = "bash start.sh && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "python init_db.py"
